### ISSUE TITLE
Loading simple save is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [wpilibsuite/shuffleboard#216]
Test:
```java
public class BasicLoadTest extends ApplicationTest {

    @Override
    public void start(Stage stage) throws Exception {
        // Just here so we can run on the FX thread
        new Shuffleboard().start(stage);
    }

    @Test
    public void loadBasicFile() {
        Reader reader = new InputStreamReader(
                getClass().getResourceAsStream("/simpleshuffleboard.json"),
                StandardCharsets.UTF_8);
        JsonBuilder.forSaveFile().fromJson(reader, DashboardTabPane.class);
    }
}
```

`simpleshuffleboard.json`
```json
[
  {
    "title": "SmartDashboard",
    "widgetPane": {
      "1,1": {
        "size": [
          1,
          1
        ],
        "content": {
          "_type": "Boolean Box",
          "_source": "example://",
          "colorWhenTrue": "#7CFC00FF",
          "colorWhenFalse": "#8B0000FF"
        }
      },
      "4,3": {
        "size": [
          2,
          1
        ],
        "content": {
          "_type": "Encoder",
          "_source": "example://"
        }
      }
    }
  },
  {
    "title": "LiveWindow",
    "widgetPane": {}
  }
]

```

Exception:
```
WARNING: Couldn't load
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at edu.wpi.first.shuffleboard.api.sources.SourceTypes.lambda$static$1(SourceTypes.java:34)
	at edu.wpi.first.shuffleboard.api.sources.SourceType.lambda$forUri$0(SourceType.java:75)
	at edu.wpi.first.shuffleboard.api.sources.Sources.lambda$computeIfAbsent$2(Sources.java:65)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at edu.wpi.first.shuffleboard.api.sources.Sources.computeIfAbsent(Sources.java:65)
	at edu.wpi.first.shuffleboard.api.sources.SourceType.forUri(SourceType.java:75)
	at edu.wpi.first.shuffleboard.api.sources.SourceTypes.forUri(SourceTypes.java:116)
	at edu.wpi.first.shuffleboard.api.sources.Sources.lambda$forUri$1(Sources.java:55)
	at edu.wpi.first.shuffleboard.api.sources.Sources.lambda$computeIfAbsent$2(Sources.java:65)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at edu.wpi.first.shuffleboard.api.sources.Sources.computeIfAbsent(Sources.java:65)
	at edu.wpi.first.shuffleboard.api.sources.Sources.forUri(Sources.java:55)
	at edu.wpi.first.shuffleboard.app.json.WidgetSaver.deserialize(WidgetSaver.java:34)
	at edu.wpi.first.shuffleboard.app.json.WidgetSaver.deserialize(WidgetSaver.java:13)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at edu.wpi.first.shuffleboard.app.json.WidgetPaneSaver.deserialize(WidgetPaneSaver.java:59)
	at edu.wpi.first.shuffleboard.app.json.WidgetPaneSaver.deserialize(WidgetPaneSaver.java:21)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at edu.wpi.first.shuffleboard.app.json.DashboardTabPaneSaver.deserialize(DashboardTabPaneSaver.java:45)
	at edu.wpi.first.shuffleboard.app.json.DashboardTabPaneSaver.deserialize(DashboardTabPaneSaver.java:16)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at edu.wpi.first.shuffleboard.app.MainWindowController.load(MainWindowController.java:360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

**Comment by nightpool** [comment]
fixed by #91
