### ISSUE TITLE
Get exception on starting Shuffleboard

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/shuffleboard#309]
```
WARNING: Uncaught exception on JavaFX Application Thread
java.lang.NullPointerException
	at edu.wpi.first.shuffleboard.api.util.PropertyUtils.bindBidirectionalWithConverter(PropertyUtils.java:45)
	at edu.wpi.first.shuffleboard.api.sources.SubSource.<init>(SubSource.java:35)
	at edu.wpi.first.shuffleboard.plugin.base.widget.PIDCommandWidget.lambda$initialize$3(PIDCommandWidget.java:46)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at edu.wpi.first.shuffleboard.api.widget.SingleSourceWidget.addSource(SingleSourceWidget.java:20)
	at edu.wpi.first.shuffleboard.app.json.SourcedRestorer.addDestroyedSourcesForAllDataTypes(SourcedRestorer.java:25)
	at edu.wpi.first.shuffleboard.app.json.WidgetSaver.deserialize(WidgetSaver.java:57)
	at edu.wpi.first.shuffleboard.app.json.WidgetSaver.deserialize(WidgetSaver.java:21)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at edu.wpi.first.shuffleboard.app.json.WidgetPaneSaver.deserialize(WidgetPaneSaver.java:59)
	at edu.wpi.first.shuffleboard.app.json.WidgetPaneSaver.deserialize(WidgetPaneSaver.java:21)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at edu.wpi.first.shuffleboard.app.json.DashboardTabPaneSaver.deserialize(DashboardTabPaneSaver.java:52)
	at edu.wpi.first.shuffleboard.app.json.DashboardTabPaneSaver.deserialize(DashboardTabPaneSaver.java:19)
	at edu.wpi.first.shuffleboard.app.json.ElementTypeAdapter.deserialize(ElementTypeAdapter.java:25)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at edu.wpi.first.shuffleboard.app.MainWindowController.load(MainWindowController.java:378)
	at edu.wpi.first.shuffleboard.app.Shuffleboard.start(Shuffleboard.java:85)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by SamCarlberg** [comment]
Looks like this was fixed by #318
