### ISSUE TITLE
Custom plugin causing IndexOutOfBoundsException

### ISSUE THREAD

**Issue by andrewda** [wpilibsuite/shuffleboard#590]
**Describe the bug**  
When using a custom plugin, I'm getting an `IndexOutOfBoundsException` after a while every time the widget should be updated, causing the entire application to hang.

<details>
 <summary>Full exception</summary>

```
Feb 27, 2019 2:40:25 PM edu.wpi.first.shuffleboard.app.Shuffleboard uncaughtException
WARNING: Uncaught exception on JavaFX Application Thread
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1701)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1645)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.intersectsBounds(Node.java:5282)
	at javafx.scene.Node$1.intersectsBounds(Node.java:548)
	at com.sun.javafx.scene.NodeHelper.intersectsBounds(NodeHelper.java:262)
	at javafx.scene.layout.Region.doPickNodeLocal(Region.java:3158)
	at javafx.scene.layout.Region.access$600(Region.java:147)
	at javafx.scene.layout.Region$1.doPickNodeLocal(Region.java:184)
	at com.sun.javafx.scene.layout.RegionHelper.pickNodeLocalImpl(RegionHelper.java:104)
	at com.sun.javafx.scene.NodeHelper.pickNodeLocal(NodeHelper.java:128)
	at javafx.scene.Node.pickNode(Node.java:5192)
	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3993)
	at javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3579)
	at javafx.scene.Scene.pick(Scene.java:2029)
	at javafx.scene.Scene.access$6800(Scene.java:172)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3805)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

<br>

Here's the plugin's source: https://github.com/SouthEugeneRoboticsTeam/sert-plugin

The widget works/updates fine for a while (no consistent amount of time, as far as I've been able to measure), but will eventually start throwing the error above at the same rate at which it's being updated by the robot code (below).

When the plugin is disabled (but the NetworkTables values still being updated) everything works as expected.

**Expected behavior**  
Custom plugins should not cause Shuffleboard to hang/crash (could very well be the fault of my plugin, but I haven't been able to come up with any reason why this would be happening).

**Desktop:**
 - OS: Windows 10 10.0 amd64
 - Java version 11.0.1+13-LTS -- Oracle Corporation
 - Version 2019.424242.4.1-20190227150115 built on February 27, 2019

**Additional context**  
Here's the relevant (Kotlin) code I'm running on the robot to update the widget. This code should update the widget with a random `backgroundColor` and an incrementing `text` value every 2 seconds.

```kotlin
class TextBox(
    var text: String = "",
    var textColor: String = "ffffff",
    var backgroundColor: String = "000000"
) : SendableBase(), Sendable {
    override fun toString() = "TextBox($text, $textColor, $backgroundColor)"

    override fun initSendable(builder: SendableBuilder) {
        builder.setSmartDashboardType("TextBox")
        builder.addStringProperty("Text", this::text, null)
        builder.addStringProperty("TextColor", this::textColor, null)
        builder.addStringProperty("BackgroundColor", this::backgroundColor, null)
    }
}

val disableBegin = Date().time
val textBox = TextBox(
    disableBegin.toString(),
    backgroundColor = "00ff00"
)

SmartDashboard.putData("Text Box", textBox)

GlobalScope.launch(MeanlibDispatcher) {
    periodic(2.0) {
        textBox.text = ((Date().time - disableBegin) / 1000).toString()
        textBox.backgroundColor = (Math.random() * 255).toInt().toString(16) +
            (Math.random() * 255).toInt().toString(16) +
            (Math.random() * 255).toInt().toString(16)

        SmartDashboard.updateValues()
    }
}
```

**Comment by andrewda** [comment]
After the error begins to occur and the application freezes, terminating the robot program (in this case I'm just running a simulation) stops the error from occurring. However, any other event in the window (e.g. a mouse over or button press) causes the same error, and the program continues to hang.

**Comment by andrewda** [comment]
Seems I accidentally came across the solution to this issue. There was a hidden error occurring when trying to parse an invalid color, and any user event that occurred then would cause the above `IndexOutOfBoundsException`. Properly handling the invalid color exception fixed this issue as far as I'm able to tell.
