### ISSUE TITLE
Cannot edit properties of Number Bars

### ISSUE THREAD

**Issue by tylertian123** [wpilibsuite/shuffleboard#634]
**Describe the bug**  
When trying to edit the properties of a Number Bar widget by right-clicking and selecting "Edit properties", the dialog to edit the properties does not show up.

**To Reproduce**  
1. Create a new Number Bar widget
2. Right-click on it and select "Edit properties"

**Expected behavior**  
A dialog should open up to allow for the editing of the properties of the Number Bar.

**Desktop (please complete the following information):**
 - OS: Linux 4.15.0-70-generic amd64 (Ubuntu 18.04.3 LTS)
 - Java version: 11.0.4
 - Version: 2020.424242.1.1-beta-2

**Additional context**  
Stack trace:
```
WARNING: Uncaught exception on JavaFX Application Thread
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheet$IntegerPropertyEditor.<init>(ExtendedPropertySheet.java:235)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheet$1.call(ExtendedPropertySheet.java:46)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheet$1.call(ExtendedPropertySheet.java:39)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin$PropertyPane.getEditor(ExtendedPropertySheetSkin.java:177)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin.addEditorForItem(ExtendedPropertySheetSkin.java:115)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin.lambda$createPropertySheetContainer$3(ExtendedPropertySheetSkin.java:87)
	at java.base/java.util.Map.forEach(Map.java:661)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin.createPropertySheetContainer(ExtendedPropertySheetSkin.java:78)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin.update(ExtendedPropertySheetSkin.java:63)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheetSkin.<init>(ExtendedPropertySheetSkin.java:54)
	at edu.wpi.first.shuffleboard.api.components.ExtendedPropertySheet.createDefaultSkin(ExtendedPropertySheet.java:191)
	at javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.scene.Scene.preferredSize(Scene.java:1745)
	at javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.stage.Window.show(Window.java:1189)
	at javafx.stage.Stage.show(Stage.java:273)
	at javafx.stage.Stage.showAndWait(Stage.java:463)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:345)
	at edu.wpi.first.shuffleboard.app.WidgetPaneController.showSettingsDialog(WidgetPaneController.java:596)
	at edu.wpi.first.shuffleboard.app.WidgetPaneController.showSettingsDialog(WidgetPaneController.java:605)
	at edu.wpi.first.shuffleboard.app.WidgetPaneController.lambda$setupTile$25(WidgetPaneController.java:361)
	at edu.wpi.first.shuffleboard.api.components.ActionList$Action.lambda$asMenuItem$0(ActionList.java:94)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:465)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by AustinShalit** [comment]
Closed by #635
