### ISSUE TITLE
Changing key throws exception

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/shuffleboard#87]
When I change the key of a key-value pair, I get this exception:

```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException
        at com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(ReadOnlyUnbackedObservableList.java:136)
        at javafx.collections.ListChangeListener$Change.getAddedSubList(ListChangeListener.java:242)
        at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.handleSelectedCellsListChangeEvent(TreeTableView.java:3244)
        at javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.access$2000(TreeTableView.java:2289)
        at javafx.scene.control.TreeTableView.sort(TreeTableView.java:1817)
        at edu.wpi.first.shuffleboard.widget.NetworkTableTreeWidget.makeBranches(NetworkTableTreeWidget.java:150)
        at edu.wpi.first.shuffleboard.widget.NetworkTableTreeWidget.lambda$null$7(NetworkTableTreeWidget.java:75)
        at java.util.HashMap.forEach(HashMap.java:1288)
        at edu.wpi.first.shuffleboard.widget.NetworkTableTreeWidget.lambda$new$8(NetworkTableTreeWidget.java:75)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
        at org.fxmisc.easybind.monadic.FlatMapBindingBase.mappedInvalidated(FlatMap.java:76)
        at org.fxmisc.easybind.monadic.FlatMapBindingBase.lambda$new$22(FlatMap.java:21)
        at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at edu.wpi.first.shuffleboard.properties.AsyncProperty.lambda$set$2(AsyncProperty.java:54)
        at edu.wpi.first.shuffleboard.util.FxUtils.runOnFxThread(FxUtils.java:45)
        at edu.wpi.first.shuffleboard.util.AsyncUtils.runAsync(AsyncUtils.java:24)
        at edu.wpi.first.shuffleboard.properties.AsyncProperty.set(AsyncProperty.java:54)
        at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
        at edu.wpi.first.shuffleboard.sources.DataSource.setData(DataSource.java:59)
        at edu.wpi.first.shuffleboard.sources.CompositeNetworkTableSource.lambda$new$0(CompositeNetworkTableSource.java:48)
        at edu.wpi.first.shuffleboard.sources.NetworkTableSource.lambda$null$0(NetworkTableSource.java:46)
        at edu.wpi.first.shuffleboard.util.FxUtils.lambda$runOnFxThread$0(FxUtils.java:49)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

Steps to reproduce:
1. Add a number to shuffleboard
2. Change the key of that value

**Comment by SamCarlberg** [comment]
This no longer seems to happen. Please re-open if you can still reproduce this bug
